### ISSUE TITLE
Support for side mouse buttons

### ISSUE THREAD

**Issue by Purarity** [xanderfrangos/global-mouse-events#4]
Possible to add support to listen to side mouse buttons XBUTTON1 and XBUTTON2?

**Comment by 0Ky** [comment]
Yes, modify the [global-mouse-events.cc](https://github.com/xanderfrangos/global-mouse-events/blob/master/global-mouse-events.cc) file, add `wParam == WM_XBUTTONUP` and `wParam == WM_XBUTTONDOWN` to the conditional statement at [lines 49 & 51](https://github.com/xanderfrangos/global-mouse-events/blob/master/global-mouse-events.cc#L49-L51), then add the following to the else-if clause at [line 64](https://github.com/xanderfrangos/global-mouse-events/blob/master/global-mouse-events.cc#L64):
```C++
} else if (GET_XBUTTON_WPARAM(nMouseData) == XBUTTON1) {
    button = 4;
} else if (GET_XBUTTON_WPARAM(nMouseData) == XBUTTON2) {
    button = 5;
}
```

**Comment by xanderfrangos** [comment]
Finally got around to adding this in v1.2.0. 👍
